{
  "server":"Неизвестная ошибка. Попробуйте еще раз!",
  "serverundefined":"Неизвестная ошибка. Попробуйте еще раз!",
  "server0":"Укажите старый пароль!",
  "server1":"E-mail введен не верно!",
  "server2":"Укажите пожалуйста ваше имя",
  "server3":"Ваш старый пароль указан не верно!",
  "server4":"Пароль указан не верно!",
  "server5":"Данный e-mail уже используется!",
  "server6":"Название\/заголовок не указано!",
  "server7":"Неправильный email или пароль!",
  "serverincorrect url":"Неверный URL",
  "collection":"Коллекция",
  "collectionNew":"Новая коллекция",
  "collectionDeleteConfirm":"Действительно удалить коллекцию?\nВсе закладки внутри коллекции будут также удалены!",
  "saveChanges":"Сохранить изменения",
  "saveError":"Произошла ошибка при сохранении!",
  "saveSuccess":"Сохранено !",
  "saved":"сохранена",
  "addSuccess":"Добавлено!",
  "moveSuccess":"Закладки успешно перемещены!",
  "removeSuccess":"Удалено!",
  "coverUpload":"Загрузка обложки",
  "fileUploadUnable":"Данный файл невозможно загрузить!",
  "fileUploadError":"Произошла ошибка при загрузке файла. Попробуйте другой файл!",
  "linkNotRecognized":"Ссылка не распознана",
  "permalink":"Ссылка на коллекцию:",
  "profile":"Профиль",
  "signIn":"Войти",
  "myCollections":"Мои коллекции",
  "save":"Сохранить",
  "remove":"Удалить",
  "elements":"закладки",
  "about":"О проекте",
  "blog":"Блог",
  "tools":"Инструменты",
  "signInSocial":"Войти с помощью",
  "signUpSocial":"Зарегистрироваться с помощью",
  "signUp":"Регистрация",
  "register":"Зарегистрироваться",
  "recoverPassword":"Восстановить пароль",
  "password":"Пароль",
  "edit":"Редактировать",
  "editMin":"Ред",
  "collectionEmpty":"Коллекция пуста",
  "recommend":"Рекомендуем",
  "installExtension":"Установить расширение",
  "extensionDescription":"Самый простой, удобный и супер быстрый\nспособ сохранить важное из интернета.",
  "enterLink":"Указать ссылку",
  "enterLinkDescription":"Укажите ссылку на любую\nстраницу, статью, фото или видео.",
  "backToCollection":"В коллекцию",
  "viewOn":"Смотреть на",
  "articled":"статью",
  "imaged":"фото",
  "videod":"контент",
  "linkd":"ссылку",
  "article":"Статья",
  "image":"Фото",
  "video":"Контент",
  "link":"Ссылка",
  "articles":"Статьи",
  "images":"Фото",
  "videos":"Контент",
  "links":"Ссылки",
  "articleSaved":"Статья сохранена",
  "imageSaved":"Фото сохранено",
  "videoSaved":"Контент сохранён",
  "linkSaved":"Ссылка сохранена",
  "articleRemoved":"Статья перенесена в корзину",
  "imageRemoved":"Фото перенесено в корзину",
  "videoRemoved":"Контент перенесен в корзину",
  "linkRemoved":"Ссылка перенесена в корзину",
  "articleRemovedPermament":"Статья удалена",
  "imageRemovedPermament":"Фото удалено",
  "videoRemovedPermament":"Контент удален",
  "linkRemovedPermament":"Ссылка удалена",
  "bookmarksRemoved":"Закладки перенесены в корзину",
  "bookmarksRemovedPermament":"Закладки удалены",
  "other":"другое",
  "vkontakte":"VK",
  "facebook":"Facebook",
  "twitter":"Twitter",
  "on":"на",
  "basicData":"Основные данные",
  "yourName":"Ваше имя",
  "changePassword":"Сменить пароль",
  "newPassword":"Новый пароль",
  "currentPassword":"Текущий пароль",
  "findBookmarkLong":"Найти закладку...",
  "nothingFound":"Ничего не найдено",
  "add":"Добавить",
  "cancel":"Отмена",
  "covers":"Обложки",
  "upload":"Загрузить",
  "imagesOnly":"Картинка не более 5 мб.",
  "uploadProgress":"Идет загрузка...",
  "fontFamily":"Семейство шрифта",
  "fontSize":"Размер шрифта",
  "interfaceStyle":"Стиль интерфейса",
  "additional":"Дополнительно",
  "fixedWidth":"Фиксированная ширина",
  "logOut":"Сменить аккаунт",
  "titleAndDescription":"Заголовок и описание",
  "title":"Заголовок",
  "description":"Описание",
  "enterTitle":"Укажите заголовок",
  "enterDescription":"Укажите описание",
  "enable":"Вкл.",
  "type":"Тип",
  "publicCollection":"Публичная коллекция",
  "shareCollection":"Поделиться коллекцией",
  "sendEmail":"Отправить по почте",
  "copyLink":"Скопировать ссылку",
  "language":"Язык",
  "iHaveAccount":"У меня уже есть аккаунт",
  "createFirstCollection":"Создать первую коллекцию",
  "checkYourEmail":"Проверьте ваш почтовый ящик!",
  "und":"и",
  "from":"от",
  "passwordChangeSuccess":"Пароль успешно изменен!",
  "smartSearch":"Умный поиск",
  "subscribe":"Подписаться",
  "youSubscribed":"Вы подписаны!",
  "subscriptions":"Подписки",
  "subscriptionsCollection":"Подписки",
  "tags":"Теги",
  "addTag":"Добавить тег",
  "noDescription":"Нет описания",
  "basic":"Основное",
  "background":"Фон",
  "removeBackground":"Удалить фон",
  "or":"или",
  "noCollections":"Нет коллекций",
  "noSubscriptions":"Нет подписок",
  "welcome":"Начните коллекционировать с",
  "publicCollections":"Публичные коллекции",
  "collectionsCount":"коллекций",
  "noPublicCollections":"Нет публичных коллекций",
  "noPublicCollectionsD":"Пользователь еще не создал либо не имеет публичных коллекции.",
  "all":"Все",
  "mobileApp":"Мобильное приложение",
  "exportBookmarks":"Экспорт закладок",
  "cover":"Обложка",
  "saveToCollection":"Сохранить в коллекцию",
  "selectCollection":"Выберите коллекцию",
  "myAccount":"Мой аккаунт",
  "enterTitleAndCollection":"Укажите заголовок и коллекцию",
  "selectPreferedType":"Выберите подходящий тип страницы",
  "back":"Назад",
  "bySort":"Отсортировано",
  "byName":"по имени",
  "byDate":"По дате",
  "findOrCreateCollection":"Найти или создать коллекцию",
  "createCollection":"Создать коллекцию",
  "createCollectionFirst":"Создать первую коллекцию...",
  "createCollectionOrDrag":"Создайте или переместите коллекцию...",
  "createGroup":"Создать группу",
  "startToSave":"Пожалуйста, войдите, чтобы начать сохранять закладки",
  "checkAgain":"Проверить еще раз!",
  "clickToMakeScreenshot":"Нажмите, чтобы создать скриншот",
  "elements1":"закладка",
  "elements2":"закладки",
  "elements5":"закладок",
  "defaultCollection-0":"Поиск",
  "defaultCollection--1":"Входящие",
  "defaultCollection--99":"Корзина",
  "byTitle":"По алфавиту",
  "saveBookmark":"Сохранить страницу",
  "saveBookmarkInInbox":"Сохранить во входящие",
  "sites":"Сайты",
  "in":"в",
  "settings":"Настройки",
  "removeCollectionSuccess":"Коллекция удалена",
  "changeIcon":"Сменить иконку",
  "group":"Группа",
  "untitled":"Безымянная",
  "removeGroupError":"Нельзя удалить не пустую группу!",
  "select":"Выбрать",
  "create":"Создать",
  "privacy":"Настройки приватности",
  "private":"Приватная",
  "privateD":"Доступна только вам",
  "public":"Публичная",
  "publicD":"Могут видеть все",
  "moveDown":"Переместить вниз",
  "moveUp":"Переместить вверх",
  "moveSelectedBookmarks":"Переместить выбранные закладки",
  "selectAll":"Выбрать все",
  "supportOnlyUrls":"Поддерживаются URL только с http и https протоколом!",
  "unableToRecognizeSpecifiedLink":"Невозможно определить указанную страницу",
  "addTags":"Добавить теги",
  "noBookmarks":"Нет закладок",
  "noBookmarksD":"Переместите ссылку или картинку со страницы, либо нажмите 'Сохранить страницу'.",
  "alreadyInCollection":"Уже в коллекции",
  "alreadyInCollectionD":"Нажмите, чтобы отредактировать описание, теги и обложку закладки",
  "alreadyInCollectionDD":"Изменить описание, теги и обложку",
  "inSocial":"Поделиться ссылкой через",
  "copyURL":"Скопировать ссылку",
  "read":"Читать",
  "smartBookmarks":"Ваши умные закладки",
  "signUpEmail":"Зарегистрироваться",
  "loginOrRegisterSocial":"Или через социальную сеть",
  "help":"Помощь",
  "name":"Имя",
  "haveIdeas":"Нашли баг или есть идея?",
  "followUsOn":"Следите за новостями и обновлениями в",
  "writeUs":"Пишите нам",
  "forDevelopers":"Разработчикам",
  "importBookmarks":"Импорт закладок",
  "howToUse":"Как пользоваться?",
  "extension":"Расширение",
  "animation":"Анимация интерфейса",
  "closeOnPageClick":"Закрывать по клику на страницу",
  "closeOnPageClickD":"Перетаскивание элементов со страницы будет не доступно",
  "helpContext":"Контекстное меню",
  "helpContextD":"Дополнительные функции доступны по нажатию правой клавиши мыши по закладкам и коллекциям",
  "helpHotKey":"Горячая клавиша",
  "helpHotKeyD":"Поменяйте в настройках расширений",
  "helpVisible":"Расширить видимую часть страницы",
  "helpVisibleD":"Подведите курсор к левому краю и нажмите на появившуюся панель",
  "helpBatch":"Множественный выбор",
  "helpBatchD":"Перемещайте или удаляйте множество закладок одновременно",
  "moreTips":"Еще советы",
  "view":"Вид",
  "openLinksInNewTab":"Открывать ссылки в новой вкладке",
  "allBookmarks":"Все закладки",
  "parent":"Родительская группа\/коллекция",
  "footerProAd":"Переходите на PRO аккаунт",
  "footerProAdD":"и получите больше возможностей",
  "onlyInPro":"Только в PRO версии",
  "nestedCollections":"Вложенные коллекции",
  "dropboxBackup":"Копия в Dropbox",
  "goToPRO":"Перейти на PRO",
  "commonSettings":"Основные настройки",
  "already":"уже находится",
  "addBookmark":"Добавить закладку",
  "addBookmarkD":"Укажите URL на страницу, статью, фото или видео",
  "advice":"Совет",
  "addAdvice":"Другие способы добавить закладку",
  "browserExtension":"Расширение для браузера",
  "androidApp":"Android приложение",
  "androidAppD":"Сохраняйте важную для вас информацию из интернета и любимых приложений в один тап!",
  "importBookmarksD":"Перенесите закладки из Google Chrome, Firefox, Safari, Opera, Pocket, Instapaper, Readability, Kippt, Delicious и других сервисов на Raindrop.io.",
  "showInDock":"Показывать в Dock",
  "showInTray":"Показывать в строке меню",
  "alwaysOnTop":"Всегда поверх всех окон",
  "blurHide":"Скрывать окно при потери фокуса",
  "desktopNeedRestart":"Перезапустите приложение, чтобы изменения вступили в силу",
  "refresh":"Обновить",
  "editProfile":"Редактировать профиль",
  "profilePage":"Моя страница",
  "upgradeAccount":"Улучшенный аккаунт",
  "screenshotError":"Невозможно сделать снимок сайта!",
  "lastWeek":"Прошлые 7 дней",
  "copyLinkToClipboard":"Скопировать адрес ссылки",
  "openInBrowser":"Открыть в браузере",
  "openInBrowserWithShift":"Чтобы открыть ссылку в браузере зажмите Ctrl или Shift",
  "selectAIconSet":"Выберите набор иконок",
  "sharing":"Совместный доступ",
  "members":"Участники",
  "enterEmails":"Укажите один или несколько email-ов через запятую...",
  "role_member":"Может редактировать",
  "role_members":"Могут редактировать",
  "role_viewer":"Только просматривать",
  "role_owner":"Владелец",
  "privateCollectionURL":"Нет публичного URL. Коллекция приватная.",
  "inviteMorePeople":"Пригласить больше людей",
  "sendInvites":"Отправить приглашения",
  "unshareCollection":"Убрать всех участников",
  "withAccessLevel":"Уровень доступа",
  "invitesSendTo":"Приглашения отправлены на",
  "unshareSuccess":"Все участники удалены",
  "accessViaLink":"Доступ по ссылке",
  "desktopIntegration":"Интеграция с приложением для Mac OS X",
  "error":"Произошла ошибка",
  "tryAgain":"Попробовать еще",
  "moveError":"Невозможно переместить!",
  "dev":"Разработчикам",
  "article1":"статья",
  "article2":"статьи",
  "article5":"статей",
  "image1":"фото",
  "image2":"фото",
  "image5":"фотографий",
  "video1":"контент",
  "video2":"контента",
  "video5":"контента",
  "link1":"ссылка",
  "link2":"ссылки",
  "link5":"ссылок",
  "createNewCollection":"Создать коллекцию",
  "toRefreshedRaindrop":"на Raindrop.io",
  "comfortableReading":"Комфортное чтение",
  "press":"СМИ",
  "subscriptionsD":"Создавайте и подписывайтесь на интересные публичные коллекции.",
  "smartSearchD":"По любым критериям, быстро и просто.",
  "tagsD":"Еще один способ организации вашей коллекции.",
  "comfortableReadingD":"Сконцентрируйтесь на чтение ваших любимых статей в удобном виде.",
  "dragNdropD":"Перемещайте ваши закладки между коллекциями.",
  "exportBookmarksD":"Чтобы иметь возможность перенести вашу коллекцию.",
  "followUs":"Следите за новостями в социальных сетях:",
  "enterSearchCriteria":"Введите через запятую критерии поиска",
  "enterSearchCriteriaD":"В любом порядке, мы сами определим, что вы имеете введу:",
  "explore":"Подборка",
  "exploreCollections":"Подборка интересных коллекций",
  "staffPicks":"Выбор редакции",
  "step":"Шаг",
  "uploadBookmarksFile":"Загрузите файл с закладками",
  "dropFilesHere":"Или перетащите файл сюда",
  "importInfo1":"HTML файл размером не более 3 мб.",
  "importInfo2":"Получить данный файл вы можете из вашего браузера или из сервиса которым вы в данный момент пользуетесь в разделе \"Экспортировать закладки\"\/\"Export bookmarks\".",
  "importInfo3":"Поддерживается Google Chrome, Mozilla Firefox, Safari, Google Bookmarks, Delicious, Kippt, Zootool или файл формата экспорта закладок Netscape.",
  "loading":"Идет загрузка",
  "noBookmarksToImport":"Нет закладок для импортирования!",
  "foldersWithBookmarks":"Папки для импортирования",
  "removeIt":"Убрать",
  "startImport":"Начать импортирование",
  "selectOtherFile":"Выбрать другой файл?",
  "importing":"Идет импортирование",
  "of":"из",
  "bookmarks":"закладок",
  "importingInfo1":"Подождите это может занять некоторое время, так как каждая из закладок будет разпознана и сохранена вместе с связанным с ней контентом.",
  "importingInfo2":"Не закрывайте данную вкладку, иначе импортирование будет остановлено!",
  "importEnd":"Импорт завершен!",
  "importSuccess":"Успешно импортировано",
  "importSuccessInfo":"Рекомендуем настроить внешний вид и иконки ваших коллекций, а также сделать публичными и рассказать о них в социальных сетях или передать ссылку друзьям.",
  "importingProcess":"Импорт закладок может занять определенное время, в зависимости от их количества! Пожалуйста наберитесь терпения, как только они будут обработаны мы оповестим вас на указанный E-mail!",
  "importingAlready":"К сожалению закладки загруженные ранее еще не обработаны! Подождите пожалуйста, мы обязательно оповестим вас по указанному E-mail.",
  "specifyYourEmail":"Пожалуйста укажите E-mail в вашем профиле!",
  "staffPicksD":"Интересные коллекции с красивым дизайном",
  "templates":"Шаблоны",
  "collectionEdit":"Редактирование коллекции",
  "raindropEdit":"Редактирование закладки",
  "icon":"Иконка",
  "selectOtherIcon":"Выбрать другую иконку...",
  "optional":"Не обязательно",
  "permamentLink":"Постоянная ссылка",
  "backgroundUploadD":"Вы можете загрузить тематический фон и придать стиль коллекции. Он будет отображаться",
  "onYourCollectionPage":"на странице вашей коллекции",
  "removeCollectionForever":"Удалить коллекцию навсегда",
  "theseAreTheBest":"Это лучшее...",
  "findCollection":"Найти коллекцию...",
  "findSubscription":"Найти подписку...",
  "more":"Еще",
  "less":"Меньше",
  "byPopularity":"By популярности",
  "collectionsSorting":"Сортировка коллекции",
  "sortBy":"Cортировать по",
  "custom":"Пользовательская",
  "byBookmarksCount":"По количеству закладок",
  "fastFilter":"Найти в открытых...",
  "fastView":"Быстрый просмотр закладок",
  "publicPage":"Ваша публичная страница",
  "welcomeSlide1D":"Сохраняйте важные ссылки, статьи, фото, видео, презентации",
  "welcomeSlide1DD":"и организовывайте их в тематические коллекции.",
  "welcomeSlide1DDD":"Ваши закладки будут доступны с компьютера и смартфона.",
  "welcomeSlide2":"Установите наше расширение",
  "welcomeSlide2D":"Самый простой, удобный и супер быстрый способ",
  "welcomeSlide2DD":"сохранить важное из интернета.",
  "next":"Далее",
  "startCollecting":"Начать коллекционировать!",
  "extensionFor":"Расширение для",
  "welcomeMobileSlide2":"Всегда с собой",
  "sourceCode":"Исходный код",
  "sourceCodeD":"Исходный код всех расширений для браузера находится в нашем",
  "sourceCodeDD":"репозитории на Github.",
  "apiD":"Документация по API находится в разработке.",
  "importFrom":"Импортировать из",
  "openCollection":"Открыть коллекцию",
  "articlesProccessing":"Полный текст статей будет загружен позже.",
  "favoriteSites":"Любимые сайты",
  "showAll":"Показать все",
  "showAllBookmarks":"Показать все закладки",
  "youHave":"У вас есть",
  "fillCollectionInput":"Вы не указали коллекцию!",
  "browserBookmarklet":"Букмарклет",
  "browserBookmarkletD":"Нет вашего браузера? Попробуйте букмарклет.",
  "browserBookmarkletDD":"Переместите эту ссылку на панель закладок",
  "browserBookmarkletDDD":"Сохранить в коллекцию",
  "hi":"Привет",
  "noTags":"Нет тегов",
  "to":"в",
  "inCollection":"в коллекции",
  "dragCollections":"Меняйте порядок коллекций простым перетаскиванием.",
  "feedAllCollections":"RSS разбитый по коллекциям",
  "orAlternativeFeed":"Все закладки",
  "feedWarning":"Внимание! Не передавайте уникальный URL ваших RSS подписок третьим лицам, так как они смогут просмотреть ваши закладки!",
  "publicRSSfeed":"Публичный RSS канал",
  "showPrivateRSSfeed":"Показать приватный RSS канал",
  "privateRSSfeed":"Приватный RSS канал",
  "mailNotifications":"E-mail оповещения",
  "disableWeeklyDigest":"Отключить персональную рассылку ваших закладок",
  "trashEmpty":"Корзина пуста",
  "forOtherBrowsers":"Для других браузеров",
  "saveLink":"Сохранить страницу",
  "instruction":"Инструкция",
  "install":"Установить",
  "importDescription":"Перенесите закладки из Google Chrome, Firefox, Safari, Opera, Pocket, Instapaper, Readability, Kippt, Delicious и других сервисов на Raindrop.io.",
  "createSubFolder":"Создать вложенную коллекция",
  "pro_nesting":"Вложенные коллекции",
  "pro_nestingD":"Бесконечные возможности для организации ваших закладок.",
  "pro_dropbox":"Копия в Dropbox",
  "pro_dropboxD":"Резервная копия закладок в вашем Dropbox.",
  "pro_support":"Приоритетная поддержка",
  "pro_supportD":"Мы поможем решить любую проблему в кратчайшие сроки.",
  "pro_nextFeatures":"Голосуй за новые функции",
  "pro_nextFeaturesD":"Пользователи PRO аккаунтов сами решают какие функции будут реализованы первыми!",
  "month":"месяц",
  "year":"год",
  "oneMonth":"Один месяц",
  "threeMonth":"3 месяца",
  "yearDiscount":"скидка, всего $19 в год!",
  "upgradeToPro":"Перейти на Pro",
  "renewPro":"Продлить подписку",
  "renewPromonth":"Продлить подписку еще на месяц",
  "renewProyear":"Продлить подписку еще на год",
  "proTitle":"Пользуйтесь Raindrop.io бесплатно",
  "proTitleD":"или перейдите на",
  "proTitleDD":"Pro аккаунт.",
  "pro_noAds":"Никакой рекламы",
  "pro_noAdsD":"",
  "pro_speed_dial":"Новая вкладка (Speed Dial)",
  "pro_apple":"Клиент для iPhone\/iPad",
  "pro_desktop":"Desktop приложение (с синхронизацией)",
  "pro_smart_collections":"Умные коллекции (атодобавление по критериям)",
  "yesIwant":"Да хочу!",
  "votes":"голос",
  "votes1":"голос",
  "votes2":"голоса",
  "votes5":"голосов",
  "whatAddNext":"Что бы вы хотели добавить?",
  "newString":"Новая",
  "newBookmark":"Новая закладка",
  "thankYou":"Спасибо!",
  "nowYouHave":"Теперь у вас",
  "account":"аккаунт",
  "goHome":"Вернуться на главную",
  "until":"до",
  "goToPayment":"Перейти к оплате",
  "subscriptionPeriod":"Срок",
  "paymentMethod":"Способ оплаты",
  "pricing":"Цены",
  "visualBookmarks":"Визуальные закладки",
  "readItLater":"Отложенное чтение статей",
  "pro_notes":"Заметки",
  "sslConnection":"Защищённое SSL-соединение",
  "browserPlugin":"Плагин для браузера",
  "features":"Возможности",
  "free":"Бесплатно",
  "removeAccount":"Удалить аккаунт",
  "removeAccountD":"Закрыть аккаунт и удалить все коллекции, закладки и сведения, которые с ними связаны?",
  "areYouSure":"Вы уверены?",
  "compareFreePro":"Сравнить бесплатный и PRO аккаунт",
  "shareLinkVia":"Поделиться ссылкой через",
  "changeAvatarInfo":"Вы можете сменить аватар привязанный к вашему Email на сайте Gravatar.com. (Граватар — это картинка, которая следует за вами от сайта к сайту, появляясь при отправке комментария или записи в блог)",
  "changeAvatar":"Сменить аватар",
  "browserExtensionD":"Доступ к коллекциям в один клик с любой вкладки браузера",
  "macApp":"Приложение для Mac OS X",
  "macAppD":"Организовывайте материалы и читайте статьи на вашем Mac",
  "macAppV":"Mac OS X (выше 10.8.0)",
  "androidAppV":"Android смартфон или планшет (выше 4.0)",
  "appleEditorsChoise":"Выбор редакции Apple",
  "operaEditorsChoise":"Рекомендует Opera",
  "downloadTitle":"Ваши закладки всегда под рукой",
  "sharedCollections":"Общие коллекции",
  "serverCollaboratorsIncorrectToken":"Невозможно стать участником коллекции. Некорректный URL. Попросите автора коллекции пригласить вас еще раз.",
  "serverCollaboratorsAlready":"Вы уже являетесь участником коллекции!",
  "joinCollaboratorsSuccess":"Поздравляем! Теперь вы стали участником коллекции.",
  "memberD":"Вы можете добавлять и редактировать закладки, создавать вложенные коллекции и приглашать новых участников.",
  "viewerD":"Вы можете только просматривать закладки в этой коллекции.",
  "savePage":"Сохранить страницу в коллекцию",
  "saveToInbox":"Быстро сохранить во входящие (Raindrop.io)",
  "saveImage":"Сохранить изображение в коллекцию",
  "myBookmarks":"Мои закладки",
  "appName":"Raindrop.io - Умные закладки",
  "appDesc":"Красивый способ запомнить самое важное.",
  "firstRun":"Для начала использования Raindrop.io вам необходимо просто обновить текущую страницу и кликнуть еще раз.",
  "refreshPage":"Обновить текущую страницу",
  "support":"Поддержка",
  "afterUpdateTitle":"Расширение обновилось",
  "afterUpdate":"Мы подготовили несколько новых функций, улучшений и исправлений. Хотите посмотреть, что нового появилось в этой версии?",
  "seeChangeLog":"Посмотреть список изменений..."
}